### ISSUE TITLE
mocha + espower-typescript で power-assert が node.js 標準の assert の動きになる

### ISSUE THREAD

**Issue by msfukui** [msfukui/programmers-math#1]
こんな感じで、power-assert の表示が有効になってくれない。困った。

```
$ npm run spec

> programmers-math@0.0.1 spec C:\Users\msfukui\My Documents\projects\programmers-math
> npm run lint && npm run spec:mocha


> programmers-math@0.0.1 lint C:\Users\msfukui\My Documents\projects\programmers-math
> tslint 'src/**/*.ts' 'spec/**/*.ts'


> programmers-math@0.0.1 spec:mocha C:\Users\msfukui\My Documents\projects\programmers-math
> mocha --require espower-typescript/guess spec/**/*.ts



  MathInduction#prove
    1) P(0) の証明結果を出力できる
    2) P(1) の証明結果を出力できる
    3) P(2) の証明結果を出力できる

  MathInduction#sum
    4) 配列の要素の和を返却する


  0 passing (80ms)
  4 failing

  1) MathInduction#prove
       P(0) の証明結果を出力できる:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.it (C:\Users\msfukui\Documents\projects\programmers-math\spec\math_induction_spec.ts:10:5)

  2) MathInduction#prove
       P(1) の証明結果を出力できる:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.it (C:\Users\msfukui\Documents\projects\programmers-math\spec\math_induction_spec.ts:20:5)

  3) MathInduction#prove
       P(2) の証明結果を出力できる:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.it (C:\Users\msfukui\Documents\projects\programmers-math\spec\math_induction_spec.ts:32:5)

  4) MathInduction#sum
       配列の要素の和を返却する:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.it (C:\Users\msfukui\Documents\projects\programmers-math\spec\math_induction_spec.ts:38:5)
```

**Comment by msfukui** [comment]
プロジェクトのディレクトリを "My Document" 配下から、$HOME/vscode 配下に移動して npm install して実行したら解消した。

依存するどれかの package が Windows 上での cygwin / msysgit 周りの環境で半角空白文字入りのフォルダに対応していないっぽい。

深堀りせずにこの場は一旦 close する。
